dataset: 'cytotox_lna'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base", "sugar", "phosphate"]
model: 'CNN'
model_args:
  depth: 1
  hidden_dim: 64
  kernel_size: 7
  pooling_operation: 'avg'
cross_validation: 'nucleobase'
