dataset: 'cytotox_lna'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base", "sugar", "phosphate"]
model: 'XGBoostModel'
model_args:
  max_depth: 20
  n_estimators: 1000
cross_validation: 'random'
