dataset: 'immune_modulation_TLR7'
featurizer: 'KMersCounts'
featurizer_args:
  k: [1, 2]
  modification_abundance: false
model: 'NearestNeighborsModel'
model_args:
  n_neighbors: 10
cross_validation: 'random'
