dataset: 'siRNA1'
featurizer: 'KMersCounts'
featurizer_args:
  k: [1, 2]
  modification_abundance: false
model: 'XGBoostModel'
model_args:
  max_depth: 30
  n_estimators: 1000
cross_validation: 'random'
