dataset: 'cytotox_lna'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base"]
model: 'Transformer'
model_args:
  d_model: 64
  dim_feedforward: 128
  dropout: 0
  nhead: 4
  num_layers: 1
cross_validation: 'nucleobase'
