dataset: 'asoptimizer_cleaned'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base"]
model: 'MLP'
model_args:
  dropout: 0.25
  hidden_dims: [128, 128]
cross_validation: 'nucleobase'
