dataset: 'sherwood'
featurizer: 'KMersCounts'
featurizer_args:
  k: [1]
  modification_abundance: true
model: 'XGBoostModel'
model_args:
  max_depth: 30
  n_estimators: 100
cross_validation: 'random'
