dataset: 'asoptimizer_cleaned'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base", "sugar", "phosphate"]
model: 'MLP'
model_args:
  dropout: 0
  hidden_dims: [64]
cross_validation: 'random'
