dataset: 'asoptimizer_cleaned'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base", "sugar", "phosphate"]
model: 'RandomForestModel'
model_args:
  max_depth: 30
  n_estimators: 100
cross_validation: 'random'
