dataset: 'sherwood'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base", "sugar", "phosphate"]
model: 'RandomForestModel'
model_args:
  max_depth: 10
  n_estimators: 1000
cross_validation: 'random'
