dataset: 'sherwood'
featurizer: 'KMersCounts'
featurizer_args:
  k: [1, 2]
  modification_abundance: false
model: 'RandomForestModel'
model_args:
  max_depth: 10
  n_estimators: 500
cross_validation: 'nucleobase'
