dataset: 'cytotox_lna'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base", "sugar", "phosphate"]
model: 'GRU'
model_args:
  hidden_dim: 32
  num_layers: 1
cross_validation: 'nucleobase'
