dataset: 'asoptimizer_cleaned'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base", "sugar", "phosphate"]
model: 'LinearModel'
model_args:
  type: 'standard'
cross_validation: 'random'
