dataset: 'cytotox_lna'
featurizer: 'OneHotEncoder'
featurizer_args:
  encode_components: ["base"]
model: 'RandomForestModel'
model_args:
  max_depth: 20
  n_estimators: 100
cross_validation: 'random'
